layout_spectrum: 0.0227656
color:
  saturation: 0.4578744
  brandStrength: 0.6716711
  lightness: 0.1644182
  rhythmicContrast: 0.4030877
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.7664418
name: Aureus Holding
